In [31]:
#here we will be getting football.csv rugby.csv and tennis.csv
#using the words in the csv files to generate a bag of words
#then we will be using the bag of words to train a classifier
#to classify tweets as football, rugby or tennis


import pandas as pd
import numpy as np

#read in the csv files, naming single column 'text'
football = pd.read_csv('football.csv', names=['text'])
rugby = pd.read_csv('rugby.csv', names=['text'])
tennis = pd.read_csv('tennis.csv', names=['text'])
esports = pd.read_csv('esports.csv', names=['text'])

football = list(football['text'])
rugby = list(rugby['text'])
tennis = list(tennis['text'])
esports = list(esports['text'])

football[:5]

['arsenal', 'liverpool', 'chelsea', 'tottenham', 'everton']

In [25]:
import sqlite3 as sql

#connect to the database
conn = sql.connect('../twitter.db')

#read a random sample of 25 tweets from the database, that are given topic "sport"
tweets = pd.read_sql_query("SELECT tweet_text FROM tweets WHERE tweet_topic='sports' ORDER BY RANDOM() LIMIT 25", conn)

#close the connection
conn.close()

tweets.head()

                                          tweet_text
0  RT @redhatphoto: A tough afternoon at the Gard...
1  I miss watching s1mple go 1-12:( was fun while...
2  A few free days for practice at #BLASTPremier,...
3  Genesis 9 Update ✅\n@DabuzSenpai advances to W...
4                     @DH_Tamil My vote is for azeem

In [36]:
#for each of football, rugby and tennis, we will count the number of times each word appears in the tweets
import re

for tweet in tweets['tweet_text']:
    #convert to lowercase
    tweet = tweet.lower()
    #remove punctuation
    tweet = re.sub(r'[^\w\s]','',tweet)
    print(tweet)
    football_count = 0
    rugby_count = 0
    tennis_count = 0
    esports_count = 0
    for word in football:
        if word in tweet:
            football_count += 1
    for word in rugby:
        if word in tweet:
            rugby_count += 1
    for word in tennis:
        if word in tweet:
            tennis_count += 1
    for word in esports:
        if word in tweet:
            esports_count += 1

    #print topic with highest count
    if rugby_count >= football_count and rugby_count >= tennis_count and rugby_count >= esports_count:
        print('rugby')
    elif football_count >= rugby_count and football_count >= tennis_count and football_count >= esports_count:
        print('football')
    elif tennis_count >= football_count and tennis_count >= rugby_count and tennis_count >= esports_count:
        print('tennis')
    elif esports_count >= football_count and esports_count >= rugby_count and esports_count >= tennis_count:
        print('esports')

rt redhatphoto a tough afternoon at the gardens  time to dust our collective selves down amp go again

pics from saintsrugby vs stadero
rugby
i miss watching s1mple go 112 was fun while it lasted
rugby
a few free days for practice at blastpremier then it is back in action against nip on monday at 1830 cet  gobig httpstcovqnnpl0rop
esports
genesis 9 update
dabuzsenpai advances to winners round of 16 over gackt from japan httpstcooylnmmukka
football
dh_tamil my vote is for azeem
rugby
rt gobigleague ᵂᴱᴿᴮᵁᴺᴳ
das big omenbyhp_de academy team kommt mit einem 1606 sieg ins halbfinale dort wartet bereits teamdeftfox auf
football
rt bigmassatm 11 in tmwt

lets go 40 vs sinners_esports
esports
rt roaring_bears ein weiterer fetter bigclangg matchday steht an

1700  cs academy vs team__spirit academy
1830  cs main vs g2e
esports
 relive the best actions from sunday morning at the 2023 rallye montecarlo

rallyemontecarlo wrc  acm_media httpstco63ue55y5b2
football
i miss watching s1mple go 112 was fun while it lasted
rugby
genesis 9 update
liquidhbox advances to losers round of 8 over s2j from california httpstcouxpuqdj0ty
rugby
congratulations to david ribbans who will join up with englandrugby this week as they begin preparations for the six nations
rugby
mindskipper i play league of legends
esports
i miss watching s1mple go 112 was fun while it lasted
rugby
rt gobigleague ᵂᴱᴿᴮᵁᴺᴳ
das big omenbyhp_de academy team kommt mit einem 1606 sieg ins halbfinale dort wartet bereits teamdeftfox auf
football
ready to kick off blastpremier spring with a banger match against g2 tomorrow  httpstcoaucl22bpib
football
chrisdo32024196 gallaghercrook tatethetalisman since time immemorial
football
ready to kick off blastpremier spring with a banger match against g2 tomorrow  httpstcoaucl22bpib
football
rt gobigleague ᵂᴱᴿᴮᵁᴺᴳ
der big omenbyhp_de academy hunt ist live
das erste match wird auf vertigo gespielt boah22

schaltet jetzt ei
football
rt gobigleague ᵂᴱᴿᴮᵁᴺᴳ
das big omenbyhp_de academy team startet mit einem 160 in den boah22 ob das der start einer neuen siegesserie
football
rt gobigleague ᵂᴱᴿᴮᵁᴺᴳ
heute ab 1545 uhr verlosen wir zusammen mit backforce_gg  2 backforce one unter den aktivsten spieler der gobig
esports
when you realize fazeclan is playing with a standin  blastpremier httpstcol168ae6vcy
esports
rt gobigleague ᵂᴱᴿᴮᵁᴺᴳ
das big omenbyhp_de academy team steht im finale des boah22
ob sie noch gestoppt werden können seht ihr auf
football
genesis 9 update
riddlesmk advances to top 64 losers round 2 over void from california httpstcoozurvtq8ww
football
rt gobigleague ᵂᴱᴿᴮᵁᴺᴳ
heute ab 1545 uhr verlosen wir zusammen mit backforce_gg  2 backforce one unter den aktivsten spieler der gobig
esports

In [ ]:
#given to arrays, calculate the cosine similarity between them
def cosine_similarity(a, b):
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot_product / (norm_a * norm_b)

#write a test function to test the cosine similarity function
def test_cosine_similarity():
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    res = cosine_similarity(a, b)
    print(res)
    assert res == 32 / np.sqrt(14 * 77)